version: '3.3'
services:
  app:
    container_name: shoping_cart
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/golang/src/app/
    depends_on:
      - postgres
    networks:
      - api
  postgres:
    image: postgres:alpine
    container_name: full_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT} 
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - api
volumes:
  api:
  database_postgres:
networks:
  api: